[versions]
agp = "8.13.0"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.3"
coreKtx = "1.17.0"
androidx-activity-compose = "1.11.0"
androidx-window = "1.5.0"
compose-plugin = "1.9.0"
kotlinxSerializationJson = "1.9.0"
xposedApi = "82"
yukihookApi = "1.3.1"
yukonga-miuix = "0.5.1"
haze = "1.6.10"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
lsplugin-apksign = { id = "org.lsposed.lsplugin.apksign", version = "1.4" }
lsplugin-resopt = { id = "org.lsposed.lsplugin.resopt", version = "1.6" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
parcelize = { id = 'kotlin-parcelize' }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }

[libraries]
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
xposedApi = { group = "de.robv.android.xposed", name = "api", version.ref = "xposedApi" }
yukihookApi = { group = "com.highcapable.yukihookapi", name = "api", version.ref = "yukihookApi" }
yukihookKsp = { group = "com.highcapable.yukihookapi", name = "ksp-xposed", version.ref = "yukihookApi" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
yukonga-miuix = { group = "top.yukonga.miuix.kmp", name = "miuix", version.ref = "yukonga-miuix" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidx-window" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
